services:
  backend:
    image: docker.io/rinex20/free_ask_internet:v2
    ports:
      - "8000:8000"
    environment:
      OPENAI_API_KEY: "sk-xxxx"
      BASE_URL: "http://192.168.88.9:11434/v1/"
      MODEL: "gpt-3.5-turbo"
      OUTPUT_REF: "False"
      SEARXNG_BASE_URL: "http://192.168.88.9:8080"
    restart: on-failure
 
  freeaskinternet-ui:
    image: docker.io/rinex20/free_ask_internet_ui:v2
    ports:
      - "3030:80"
    environment:
      BACKEND_HOST: "backend:8000"
    depends_on:
      - backend
    restart: always
